datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true

## Sidecars that collect the configmaps with specified label and stores the included files them into the respective folders
## Requires at least Grafana 5 to work and can't be used together with parameters dashboardProviders, datasources and dashboards
sidecar:
  dashboards:
    enabled: true

# Expose Grafana service externally for e2e tests
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  annotations: {}
  labels: {}
